export const errorMessages = Object.freeze({
    INVALID_EMAIL: "Invalid email",
    INVALID_PASSWORD: "Invalid password",
    EMAIL_EXISTED: "Email already exists",
    NOT_FOUND: "Not found",
    ERROR_SERVER: "Server error",
    EMAIL_NOT_FOUND: "Email not found",
    PASSWORD_NOT_MATCH: "Password is wrong",
    TOKEN_INVALID: "Token invalid",
    DELETE_FAIL: "Delete fail",
    CREATE_FAIL: "Create fail",
    UPDATE_FAIL: "Update fail",
    REGISTER_FALL: "Register failed",
    LOGIN_FALL: "Login failed",
  });
  
  export const successMessages = Object.freeze({
    REGISTER_SUCCESS: "Register successfully!",
    LOGIN_SUCCESS: "Login successfully!",
    GET_USER_SUCCESS: "Get user successfully!",
    UPDATE_USER_SUCCESS: "Update user successfully!",
    DELETE_USER_SUCCESS: "Delete user successfully!",
    GET_PROFILE_SUCCESS: "Get profile successfully!",
    RESET_PASSWORD_SUCCESS: "Reset password successfully!",
    UPDATE_PROFILE_SUCCESS: "Update profile successfully!",
    GET_PRODUCT_SUCCESS: "Get product successfully!",
    CREATE_PRODUCT_SUCCESS: "Create product successfully!",
    UPDATE_PRODUCT_SUCCESS: "Update product successfully!",
    DELETE_PRODUCT_SUCCESS: "Delete product successfully!",
  });