export const errorMessages = Object.freeze({
  INVALID_EMAIL: "Invalid email",
  INVALID_PASSWORD: "Invalid password",
  INVALID_BODY_REQUEST: "Invalid body request",
  EMAIL_EXISTED: "Email already exists",
  NOT_FOUND: "Not found",
  ERROR_SERVER: "Server error",
  EMAIL_NOT_FOUND: "Email not found",
  PASSWORD_NOT_MATCH: "Password not match",
  TOKEN_INVALID: "Token invalid",
  GET_FAIL: "Get data failed",
  CREATE_FAIL: "Create data failed",
  UPDATE_FAIL: "Update data failed",
  DELETE_FAIL: "Delete data failed",
  PERMISSION_DENIED: "Permission denied",
  REGISTER_FAILED: "Register failed",
  LOGIN_FAILED: "Login failed",
});

export const successMessages = Object.freeze({
  REGISTER_SUCCESS: "Register successfully!",
  LOGIN_SUCCESS: "Login successfully!",
  GET_USER_SUCCESS: "Get user successfully!",
  UPDATE_USER_SUCCESS: "Update user successfully!",
  DELETE_USER_SUCCESS: "Delete user successfully!",
  GET_PROFILE_SUCCESS: "Get profile successfully!",
  RESET_PASSWORD_SUCCESS: "Reset password successfully!",
  UPDATE_PROFILE_SUCCESS: "Update profile successfully!",
  GET_DATA_SUCCESS: "Get data successfully!",
  CREATE_DATA_SUCCESS: "Create data successfully!",
  UPDATE_DATA_SUCCESS: "Update data successfully!",
  DELETE_DATA_SUCCESS: "Delete data successfully!",
});
